create table todos (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
); 